### ISSUE TITLE
TENCENT_APP_ID

### ISSUE THREAD

**Issue by laowangDemon** [Coder-ZhaoLu/Getx-PinkApp#1]
Attribute data@scheme at AndroidManifest.xml requires a placeholder substitution but no value for <TENCENT_APP_ID> is provided.

**Comment by axelulu** [comment]
app中用的是这个插件 [链接](https://pub.dev/packages/tencent_kit)  ，你可以参考一下这个插件使用方法

**Comment by laowangDemon** [comment]
感谢作者大大，这是因为有些配置被我删除了
你这个界面做的挺精美的
