### ISSUE TITLE
NavigationBar

### ISSUE THREAD

**Issue by laowangDemon** [Coder-ZhaoLu/Getx-PinkApp#2]
lib/app/modules/aboutApp/views/about_app_view.dart:29:12: Error: 'NavigationBar' is imported from both 'package:flutter/src/material/navigation_bar.dart' and 'package:pink_acg/app/widget/navigation_bar.dart'.
    return NavigationBar(
           ^^^^^^^^^^^^^
lib/app/modules/aboutUs/views/about_us_view.dart:27:12: Error: 'NavigationBar' is imported from both 'package:flutter/src/material/navigation_bar.dart' and 'package:pink_acg/app/widget/navigation_bar.dart'.
    return NavigationBar(
           ^^^^^^^^^^^^^
lib/app/modules/chat/views/chat_view.dart:63:12: Error: 'NavigationBar' is imported from both 'package:flutter/src/material/navigation_bar.dart' and 'package:pink_acg/app/widget/navigation_bar.dart'.
    return NavigationBar(
           ^^^^^^^^^^^^^
lib/app/modules/contact/views/contact_view.dart:41:12: Error: 'NavigationBar' is imported from both 'package:flutter/src/material/navigation_bar.dart' and 'package:pink_acg/app/widget/navigation_bar.dart'.
    return NavigationBar(
           ^^^^^^^^^^^^^
lib/app/modules/darkMode/views/dark_mode_view.dart:26:12: Error: 'NavigationBar' is imported from both 'package:flutter/src/material/navigation_bar.dart' and 'package:pink_acg/app/widget/navigation_bar.dart'.
    return NavigationBar(
           ^^^^^^^^^^^^^
lib/app/modules/dynamic/views/dynamic_view.dart:29:12: Error: 'NavigationBar' is imported from both 'package:flutter/src/material/navigation_bar.dart' and 'package:pink_acg/app/widget/navigation_bar.dart'.
    return NavigationBar(
           ^^^^^^^^^^^^^
lib/app/modules/home/views/home_view.dart:69:12: Error: 'NavigationBar' is imported from both 'package:flutter/src/material/navigation_bar.dart' and 'package:pink_acg/app/widget/navigation_bar.dart'.
    return NavigationBar(
           ^^^^^^^^^^^^^
lib/app/modules/profile/views/profile_view.dart:33:12: Error: 'NavigationBar' is imported from both 'package:flutter/src/material/navigation_bar.dart' and 'package:pink_acg/app/widget/navigation_bar.dart'.
    return NavigationBar(
           ^^^^^^^^^^^^^
lib/app/modules/profileFollow/views/profile_follow_view.dart:29:12: Error: 'NavigationBar' is imported from both 'package:flutter/src/material/navigation_bar.dart' and 'package:pink_acg/app/widget/navigation_bar.dart'.
    return NavigationBar(
           ^^^^^^^^^^^^^
lib/app/modules/profilePost/views/profile_post_view.dart:29:12: Error: 'NavigationBar' is imported from both 'package:flutter/src/material/navigation_bar.dart' and 'package:pink_acg/app/widget/navigation_bar.dart'.
    return NavigationBar(
           ^^^^^^^^^^^^^
lib/app/modules/publish/views/publish_view.dart:80:12: Error: 'NavigationBar' is imported from both 'package:flutter/src/material/navigation_bar.dart' and 'package:pink_acg/app/widget/navigation_bar.dart'.
    return NavigationBar(
           ^^^^^^^^^^^^^
lib/app/modules/rank/views/rank_view.dart:26:12: Error: 'NavigationBar' is imported from both 'package:flutter/src/material/navigation_bar.dart' and 'package:pink_acg/app/widget/navigation_bar.dart'.
    return NavigationBar(
           ^^^^^^^^^^^^^
lib/app/modules/search/views/search_view.dart:22:11: Error: 'NavigationBar' is imported from both 'package:flutter/src/material/navigation_bar.dart' and 'package:pink_acg/app/widget/navigation_bar.dart'.
          NavigationBar(
          ^^^^^^^^^^^^^
lib/app/modules/setting/views/setting_view.dart:32:12: Error: 'NavigationBar' is imported from both 'package:flutter/src/material/navigation_bar.dart' and 'package:pink_acg/app/widget/navigation_bar.dart'.
    return NavigationBar(
           ^^^^^^^^^^^^^
lib/app/modules/userDesc/views/user_desc_view.dart:29:12: Error: 'NavigationBar' is imported from both 'package:flutter/src/material/navigation_bar.dart' and 'package:pink_acg/app/widget/navigation_bar.dart'.
    return NavigationBar(
           ^^^^^^^^^^^^^
lib/app/modules/userEmail/views/user_email_view.dart:15:12: Error: 'NavigationBar' is imported from both 'package:flutter/src/material/navigation_bar.dart' and 'package:pink_acg/app/widget/navigation_bar.dart'.
    return NavigationBar(
           ^^^^^^^^^^^^^
lib/app/modules/userInfo/views/user_info_view.dart:36:12: Error: 'NavigationBar' is imported from both 'package:flutter/src/material/navigation_bar.dart' and 'package:pink_acg/app/widget/navigation_bar.dart'.
    return NavigationBar(
           ^^^^^^^^^^^^^
lib/app/modules/userPwd/views/user_pwd_view.dart:15:12: Error: 'NavigationBar' is imported from both 'package:flutter/src/material/navigation_bar.dart' and 'package:pink_acg/app/widget/navigation_bar.dart'.
    return NavigationBar(
           ^^^^^^^^^^^^^
lib/app/modules/userQrcode/views/user_qrcode_view.dart:17:12: Error: 'NavigationBar' is imported from both 'package:flutter/src/material/navigation_bar.dart' and 'package:pink_acg/app/widget/navigation_bar.dart'.
    return NavigationBar(
           ^^^^^^^^^^^^^
lib/app/modules/userUsername/views/user_username_view.dart:29:12: Error: 'NavigationBar' is imported from both 'package:flutter/src/material/navigation_bar.dart' and 'package:pink_acg/app/widget/navigation_bar.dart'.
    return NavigationBar(
           ^^^^^^^^^^^^^
lib/app/modules/video/views/video_view.dart:192:11: Error: 'NavigationBar' is imported from both 'package:flutter/src/material/navigation_bar.dart' and 'package:pink_acg/app/widget/navigation_bar.dart'.
          NavigationBar(
          ^^^^^^^^^^^^^

**Comment by axelulu** [comment]
flutter2.8重名了，你可以改个名字

**Comment by laowangDemon** [comment]
好迅速，好的

**Comment by laowangDemon** [comment]
> flutter2.8重名了，你可以改个名字



> lib/app/modules/aboutApp/views/about_app_view.dart:29:12: Error: 'NavigationBar' is imported from both 'package:flutter/src/material/navigation_bar.dart' and 'package:pink_acg/app/widget/navigation_bar.dart'. return NavigationBar( ^^^^^^^^^^^^^ lib/app/modules/aboutUs/views/about_us_view.dart:27:12: Error: 'NavigationBar' is imported from both 'package:flutter/src/material/navigation_bar.dart' and 'package:pink_acg/app/widget/navigation_bar.dart'. return NavigationBar( ^^^^^^^^^^^^^ lib/app/modules/chat/views/chat_view.dart:63:12: Error: 'NavigationBar' is imported from both 'package:flutter/src/material/navigation_bar.dart' and 'package:pink_acg/app/widget/navigation_bar.dart'. return NavigationBar( ^^^^^^^^^^^^^ lib/app/modules/contact/views/contact_view.dart:41:12: Error: 'NavigationBar' is imported from both 'package:flutter/src/material/navigation_bar.dart' and 'package:pink_acg/app/widget/navigation_bar.dart'. return NavigationBar( ^^^^^^^^^^^^^ lib/app/modules/darkMode/views/dark_mode_view.dart:26:12: Error: 'NavigationBar' is imported from both 'package:flutter/src/material/navigation_bar.dart' and 'package:pink_acg/app/widget/navigation_bar.dart'. return NavigationBar( ^^^^^^^^^^^^^ lib/app/modules/dynamic/views/dynamic_view.dart:29:12: Error: 'NavigationBar' is imported from both 'package:flutter/src/material/navigation_bar.dart' and 'package:pink_acg/app/widget/navigation_bar.dart'. return NavigationBar( ^^^^^^^^^^^^^ lib/app/modules/home/views/home_view.dart:69:12: Error: 'NavigationBar' is imported from both 'package:flutter/src/material/navigation_bar.dart' and 'package:pink_acg/app/widget/navigation_bar.dart'. return NavigationBar( ^^^^^^^^^^^^^ lib/app/modules/profile/views/profile_view.dart:33:12: Error: 'NavigationBar' is imported from both 'package:flutter/src/material/navigation_bar.dart' and 'package:pink_acg/app/widget/navigation_bar.dart'. return NavigationBar( ^^^^^^^^^^^^^ lib/app/modules/profileFollow/views/profile_follow_view.dart:29:12: Error: 'NavigationBar' is imported from both 'package:flutter/src/material/navigation_bar.dart' and 'package:pink_acg/app/widget/navigation_bar.dart'. return NavigationBar( ^^^^^^^^^^^^^ lib/app/modules/profilePost/views/profile_post_view.dart:29:12: Error: 'NavigationBar' is imported from both 'package:flutter/src/material/navigation_bar.dart' and 'package:pink_acg/app/widget/navigation_bar.dart'. return NavigationBar( ^^^^^^^^^^^^^ lib/app/modules/publish/views/publish_view.dart:80:12: Error: 'NavigationBar' is imported from both 'package:flutter/src/material/navigation_bar.dart' and 'package:pink_acg/app/widget/navigation_bar.dart'. return NavigationBar( ^^^^^^^^^^^^^ lib/app/modules/rank/views/rank_view.dart:26:12: Error: 'NavigationBar' is imported from both 'package:flutter/src/material/navigation_bar.dart' and 'package:pink_acg/app/widget/navigation_bar.dart'. return NavigationBar( ^^^^^^^^^^^^^ lib/app/modules/search/views/search_view.dart:22:11: Error: 'NavigationBar' is imported from both 'package:flutter/src/material/navigation_bar.dart' and 'package:pink_acg/app/widget/navigation_bar.dart'. NavigationBar( ^^^^^^^^^^^^^ lib/app/modules/setting/views/setting_view.dart:32:12: Error: 'NavigationBar' is imported from both 'package:flutter/src/material/navigation_bar.dart' and 'package:pink_acg/app/widget/navigation_bar.dart'. return NavigationBar( ^^^^^^^^^^^^^ lib/app/modules/userDesc/views/user_desc_view.dart:29:12: Error: 'NavigationBar' is imported from both 'package:flutter/src/material/navigation_bar.dart' and 'package:pink_acg/app/widget/navigation_bar.dart'. return NavigationBar( ^^^^^^^^^^^^^ lib/app/modules/userEmail/views/user_email_view.dart:15:12: Error: 'NavigationBar' is imported from both 'package:flutter/src/material/navigation_bar.dart' and 'package:pink_acg/app/widget/navigation_bar.dart'. return NavigationBar( ^^^^^^^^^^^^^ lib/app/modules/userInfo/views/user_info_view.dart:36:12: Error: 'NavigationBar' is imported from both 'package:flutter/src/material/navigation_bar.dart' and 'package:pink_acg/app/widget/navigation_bar.dart'. return NavigationBar( ^^^^^^^^^^^^^ lib/app/modules/userPwd/views/user_pwd_view.dart:15:12: Error: 'NavigationBar' is imported from both 'package:flutter/src/material/navigation_bar.dart' and 'package:pink_acg/app/widget/navigation_bar.dart'. return NavigationBar( ^^^^^^^^^^^^^ lib/app/modules/userQrcode/views/user_qrcode_view.dart:17:12: Error: 'NavigationBar' is imported from both 'package:flutter/src/material/navigation_bar.dart' and 'package:pink_acg/app/widget/navigation_bar.dart'. return NavigationBar( ^^^^^^^^^^^^^ lib/app/modules/userUsername/views/user_username_view.dart:29:12: Error: 'NavigationBar' is imported from both 'package:flutter/src/material/navigation_bar.dart' and 'package:pink_acg/app/widget/navigation_bar.dart'. return NavigationBar( ^^^^^^^^^^^^^ lib/app/modules/video/views/video_view.dart:192:11: Error: 'NavigationBar' is imported from both 'package:flutter/src/material/navigation_bar.dart' and 'package:pink_acg/app/widget/navigation_bar.dart'. NavigationBar( ^^^^^^^^^^^^^ ../../Desktop/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image-5.1.3/lib/src/gesture_detector/scale.dart:32:11: Error: No named parameter with the name 'delta'. delta: delta, ^^^^^ ../../Desktop/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image-5.1.3/lib/src/gesture_detector/scale.dart:339:43: Error: Too few positional arguments: 2 required, 1 given. focalPointDelta > computePanSlop(pointerDeviceKind)) ^ ../../Desktop/flutter/packages/flutter/lib/src/gestures/events.dart:2116:8: Context: Found this candidate, but the arguments don't match. double computePanSlop(PointerDeviceKind kind, DeviceGestureSettings? settings) { ^^^^^^^^^^^^^^ ../../Desktop/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image-5.1.3/lib/src/gesture_detector/drag.dart:46:66: Error: Too few positional arguments: 2 required, 1 given. final double minDistance = minFlingDistance ?? computeHitSlop(kind); ^ ../../Desktop/flutter/packages/flutter/lib/src/gestures/events.dart:2103:8: Context: Found this candidate, but the arguments don't match. double computeHitSlop(PointerDeviceKind kind, DeviceGestureSettings? settings) { ^^^^^^^^^^^^^^ ../../Desktop/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image-5.1.3/lib/src/gesture_detector/drag.dart:54:55: Error: Too few positional arguments: 2 required, 1 given. return _globalDistanceMoved.abs() > computeHitSlop(pointerDeviceKind); ^ ../../Desktop/flutter/packages/flutter/lib/src/gestures/events.dart:2103:8: Context: Found this candidate, but the arguments don't match. double computeHitSlop(PointerDeviceKind kind, DeviceGestureSettings? settings) { ^^^^^^^^^^^^^^ ../../Desktop/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image-5.1.3/lib/src/gesture_detector/drag.dart:101:66: Error: Too few positional arguments: 2 required, 1 given. final double minDistance = minFlingDistance ?? computeHitSlop(kind); ^ ../../Desktop/flutter/packages/flutter/lib/src/gestures/events.dart:2103:8: Context: Found this candidate, but the arguments don't match. double computeHitSlop(PointerDeviceKind kind, DeviceGestureSettings? settings) { ^^^^^^^^^^^^^^ ../../Desktop/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image-5.1.3/lib/src/gesture_detector/drag.dart:109:55: Error: Too few positional arguments: 2 required, 1 given. return _globalDistanceMoved.abs() > computeHitSlop(pointerDeviceKind); ^ ../../Desktop/flutter/packages/flutter/lib/src/gestures/events.dart:2103:8: Context: Found this candidate, but the arguments don't match. double computeHitSlop(PointerDeviceKind kind, DeviceGestureSettings? settings) {
