### ISSUE TITLE
flutter新手，这个感觉像是我flutter版本问题，Flutter 2.8.1，不知作者大大什么版本

### ISSUE THREAD

**Issue by laowangDemon** [Coder-ZhaoLu/Getx-PinkApp#3]
../../Desktop/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image-5.1.3/lib/src/gesture_detector/scale.dart:32:11: Error: No named parameter with the name 'delta'.
          delta: delta,
          ^^^^^
../../Desktop/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image-5.1.3/lib/src/gesture_detector/scale.dart:339:43: Error: Too few positional arguments: 2 required, 1 given.
          focalPointDelta > computePanSlop(pointerDeviceKind))
                                          ^
../../Desktop/flutter/packages/flutter/lib/src/gestures/events.dart:2116:8: Context: Found this candidate, but the arguments don't match.
double computePanSlop(PointerDeviceKind kind, DeviceGestureSettings? settings) {
       ^^^^^^^^^^^^^^
../../Desktop/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image-5.1.3/lib/src/gesture_detector/drag.dart:46:66: Error: Too few positional arguments: 2 required, 1 given.
    final double minDistance = minFlingDistance ?? computeHitSlop(kind);
                                                                 ^
../../Desktop/flutter/packages/flutter/lib/src/gestures/events.dart:2103:8: Context: Found this candidate, but the arguments don't match.
double computeHitSlop(PointerDeviceKind kind, DeviceGestureSettings? settings) {
       ^^^^^^^^^^^^^^
../../Desktop/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image-5.1.3/lib/src/gesture_detector/drag.dart:54:55: Error: Too few positional arguments: 2 required, 1 given.
    return _globalDistanceMoved.abs() > computeHitSlop(pointerDeviceKind);
                                                      ^
../../Desktop/flutter/packages/flutter/lib/src/gestures/events.dart:2103:8: Context: Found this candidate, but the arguments don't match.
double computeHitSlop(PointerDeviceKind kind, DeviceGestureSettings? settings) {
       ^^^^^^^^^^^^^^
../../Desktop/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image-5.1.3/lib/src/gesture_detector/drag.dart:101:66: Error: Too few positional arguments: 2 required, 1 given.
    final double minDistance = minFlingDistance ?? computeHitSlop(kind);
                                                                 ^
../../Desktop/flutter/packages/flutter/lib/src/gestures/events.dart:2103:8: Context: Found this candidate, but the arguments don't match.
double computeHitSlop(PointerDeviceKind kind, DeviceGestureSettings? settings) {
       ^^^^^^^^^^^^^^
../../Desktop/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image-5.1.3/lib/src/gesture_detector/drag.dart:109:55: Error: Too few positional arguments: 2 required, 1 given.
    return _globalDistanceMoved.abs() > computeHitSlop(pointerDeviceKind);
                                                      ^
../../Desktop/flutter/packages/flutter/lib/src/gestures/events.dart:2103:8: Context: Found this candidate, but the arguments don't match.
double computeHitSlop(PointerDeviceKind kind, DeviceGestureSettings? settings) {

**Comment by laowangDemon** [comment]
这应该是rich_editor中extended_image版本问题，正在查看修复

**Comment by axelulu** [comment]
我是2.5版本的时候开发的，现在升级了2.8，还没跑过

**Comment by laowangDemon** [comment]
升级wechat_assets_picker: ^6.3.1
  wechat_camera_picker: ^2.6.3
后能够正常运行
